{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPNoYBafPIL0GhjVBcfw0LG",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/seeeeeeeeeeun/health/blob/main/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "7ddvrGR7T5vb"
      },
      "outputs": [],
      "source": [
        "import gradio as gr\n",
        "import os\n",
        "import random\n",
        "from io import BytesIO\n",
        "from PIL import Image\n",
        "\n",
        "# ⚠️ Gemini API 클라이언트 초기화 ⚠️\n",
        "# API 키는 환경 변수(GEMINI_API_KEY)에서 자동으로 가져옵니다.\n",
        "# Render/Railway에 배포할 때 이 환경 변수를 설정해야 합니다.\n",
        "try:\n",
        "    from google import genai\n",
        "    from google.genai.types import GenerateImagesConfig\n",
        "    client = genai.Client()\n",
        "    # 이미지 생성에 최적화된 모델 사용\n",
        "    IMAGE_MODEL = 'imagen-3.0-generate-002'\n",
        "except Exception as e:\n",
        "    # API 키가 없거나 라이브러리 초기화 실패 시 더미 클라이언트 사용\n",
        "    print(f\"Gemini 클라이언트 초기화 실패: {e}. 더미 모드로 실행됩니다.\")\n",
        "    client = None\n",
        "    IMAGE_MODEL = \"Dummy Mode\"\n",
        "\n",
        "# --- 1. 프롬프트 생성에 사용될 데이터 및 맵핑 ---\n",
        "# 모든 캐릭터에 일관성을 부여하는 핵심 키워드\n",
        "BASE_STYLE = \"cute anthropomorphic pudding character, thick black outline, 2D minimalist sticker style, no frosting or cream, clean white background, digital art\"\n",
        "NEGATIVE_PROMPT = \"blurry, distorted, ugly, bad anatomy, realistic, 3D, complex background, text\"\n",
        "\n",
        "# Q1: 에너지 유형 -> 푸딩 맛(색깔) 결정\n",
        "FLAVOR_MAP = {\n",
        "    \"외향\": \"vibrant strawberry red pudding\",\n",
        "    \"내향\": \"calm indigo blueberry pudding\",\n",
        "}\n",
        "\n",
        "# Q5: 데이트 선호 분위기 -> 행동/배경 결정\n",
        "BEHAVIOR_MAP = {\n",
        "    \"잔잔함\": \"sitting by a window, reading a book calmly, small smile\",\n",
        "    \"활발함\": \"jumping energetically, wearing running shoes\",\n",
        "    \"탐험·액티비티\": \"climbing a small mountain peak, looking adventurous\",\n",
        "    \"예술적\": \"holding a small paintbrush, standing next to an easel\",\n",
        "    \"감성적\": \"looking up at the sunset with a thoughtful expression\",\n",
        "}\n",
        "\n",
        "# Q10: 가치관 우선순위 -> 성격 강조\n",
        "VALUE_ADJECTIVE_MAP = {\n",
        "    \"안정감\": \"wearing a cozy scarf, looking secure and reliable\",\n",
        "    \"설렘\": \"with sparkling eyes, looking excited and enthusiastic\",\n",
        "    \"성장\": \"holding a small sprout, looking determined and hopeful\",\n",
        "    \"유머\": \"winking, wearing a funny tiny hat, looking playful\",\n",
        "    \"배려\": \"offering a flower to the viewer, looking gentle and kind\",\n",
        "}\n",
        "\n",
        "def generate_character_prompt(energy_type, date_mood, priority_value):\n",
        "    \"\"\"\n",
        "    사용자의 답변을 기반으로 Gemini용 이미지 생성 프롬프트를 생성합니다.\n",
        "    \"\"\"\n",
        "    # 1. 푸딩 맛 (Flavor)\n",
        "    flavor = FLAVOR_MAP.get(energy_type, \"classic caramel brown pudding\")\n",
        "\n",
        "    # 2. 행동/배경 (Behavior/Context)\n",
        "    behavior = BEHAVIOR_MAP.get(date_mood, \"smiling happily\")\n",
        "\n",
        "    # 3. 가치관 (Value) 강조\n",
        "    value_adjective = VALUE_ADJECTIVE_MAP.get(priority_value, \"happy\")\n",
        "\n",
        "    # 최종 프롬프트 조합\n",
        "    final_prompt = f\"{flavor}, {value_adjective}, {behavior}. {BASE_STYLE}\"\n",
        "\n",
        "    # 키워드 설명 생성 (Gradio 출력용)\n",
        "    description = (\n",
        "        f\"**에너지 유형:** {energy_type} (푸딩 맛: {flavor.split()[0].capitalize()})\\n\"\n",
        "        f\"**데이트 분위기:** {date_mood} (행동: {behavior})\\n\"\n",
        "        f\"**중요 가치:** {priority_value} ({value_adjective})\"\n",
        "    )\n",
        "\n",
        "    return final_prompt, description\n",
        "\n",
        "def generate_image_from_gemini(prompt, negative_prompt, seed=None):\n",
        "    \"\"\"\n",
        "    Gemini API를 호출하여 이미지를 생성하고 PIL Image 객체를 반환합니다.\n",
        "    \"\"\"\n",
        "    if client is None:\n",
        "        # 더미 모드일 경우 빈 이미지 반환\n",
        "        return Image.new('RGB', (512, 512), color='lightgray'), \"API KEY NOT SET (Dummy Image)\"\n",
        "\n",
        "    try:\n",
        "        # 프롬프트 구성\n",
        "        full_prompt = f\"{prompt}. --ar 1:1\"\n",
        "\n",
        "        # 이미지 생성 요청\n",
        "        result = client.models.generate_images(\n",
        "            model=IMAGE_MODEL,\n",
        "            prompt=full_prompt,\n",
        "            config=GenerateImagesConfig(\n",
        "                number_of_images=1,\n",
        "                negative_prompt=negative_prompt,\n",
        "            )\n",
        "        )\n",
        "\n",
        "        # 생성된 이미지 데이터(바이트)를 PIL Image 객체로 변환\n",
        "        image_bytes = result.generated_images[0].image.image_bytes\n",
        "        image = Image.open(BytesIO(image_bytes))\n",
        "\n",
        "        return image, \"성공적으로 생성됨\"\n",
        "\n",
        "    except Exception as e:\n",
        "        error_msg = f\"API 호출 오류: {e}\"\n",
        "        # 오류 시 오류 메시지와 빈 이미지 반환\n",
        "        return Image.new('RGB', (512, 512), color='red'), error_msg\n",
        "\n",
        "\n",
        "# --- 2. Gradio 인터페이스 구축 ---\n",
        "with gr.Blocks() as demo:\n",
        "    gr.Markdown(\"# 🍮 AI 푸딩 캐릭터 소개팅 타입 테스트 (Gemini Image Generation)\")\n",
        "    gr.Markdown(\"답변을 입력하고, 나만의 성향을 가진 푸딩 캐릭터를 실시간으로 확인하세요!\")\n",
        "\n",
        "    with gr.Row():\n",
        "        with gr.Column(scale=1):\n",
        "            # Q1: 에너지 유형\n",
        "            q1 = gr.Radio(list(FLAVOR_MAP.keys()), label=\"Q1. 에너지는 어디에서 얻나요?\", value=list(FLAVOR_MAP.keys())[0])\n",
        "            # Q5: 데이트 선호 분위기\n",
        "            q5 = gr.Radio(list(BEHAVIOR_MAP.keys()), label=\"Q5. 선호하는 데이트 분위기는?\", value=list(BEHAVIOR_MAP.keys())[0])\n",
        "            # Q10: 가치관 우선순위\n",
        "            q10 = gr.Radio(list(VALUE_ADJECTIVE_MAP.keys()), label=\"Q10. 연인에게 가장 중요한 가치는?\", value=list(VALUE_ADJECTIVE_MAP.keys())[0])\n",
        "\n",
        "            generate_btn = gr.Button(\"내 푸딩 캐릭터 생성하기!\")\n",
        "\n",
        "        with gr.Column(scale=2):\n",
        "            output_image = gr.Image(label=\"나의 성향 푸딩 캐릭터\", type=\"pil\")\n",
        "            output_description = gr.Markdown(\"---\")\n",
        "            output_prompt = gr.Textbox(label=\"AI 전달 프롬프트\", interactive=False, visible=False)\n",
        "            output_status = gr.Textbox(label=\"상태\", interactive=False)\n",
        "\n",
        "    def process_all_questions(energy, mood, value):\n",
        "        # 1. 프롬프트 및 설명 생성\n",
        "        prompt, description = generate_character_prompt(energy, mood, value)\n",
        "\n",
        "        # 2. 이미지 생성\n",
        "        image, status = generate_image_from_gemini(prompt, NEGATIVE_PROMPT)\n",
        "\n",
        "        # 3. 결과 반환\n",
        "        return image, description, prompt, status\n",
        "\n",
        "    # 버튼 클릭 시 함수 연결\n",
        "    generate_btn.click(\n",
        "        fn=process_all_questions,\n",
        "        inputs=[q1, q5, q10],\n",
        "        outputs=[output_image, output_description, output_prompt, output_status]\n",
        "    )\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    # Render/Railway 배포 시 port 7860이 사용될 수 있습니다.\n",
        "    demo.launch()"
      ]
    }
  ]
}